<?php
/**
 * Html Tag Constructor
 *
 * Demo page
 *
 * @author Konstantin Kutsevalov
 * @email <mail@art-prog.ru>
 */

require dirname(__FILE__) . '/Tag.php';

use \adamasantares\html\Tag;
use function \adamasantares\html\tg;


echo tg(['html5', 'lang' => 'en'], [
    tg('head', [
        tg('meta%charset', 'utf-8'),
        tg('title', 'Demo page of Tag generator'),
        tg('meta$author', 'Adamas Antares'),
        tg('meta$description', 'Just an experiment of HTML tags constructor'),
        tg('meta$keywords', 'experiment, HTML tags, constructor'),
        tg('link@icon!image/x-icon', '/favicon.ico'),
        tg('link@stylesheet', '/style.css'),
    ]),
    tg('body.demo-page', [
        tg('h1', 'Demo page'),
        tg('p.info', 'This page was generated by Tag objects, there is no any tags in source code.'),
        tg('h2', 'Form example'),
        tg('.form-example',
            tg(['form$demoform.no-submit', 'action' => '/'], [
                tg('label', ['User name', 'br/',
                    tg('input!text$username.field', '')
                ]),
                tg('label', ['Email', 'br/',
                    tg('input!email$email.field', '')
                ]),
                tg('label', ['Password', 'br/',
                    tg('input!password$pwd.field', '')
                ]),
                tg('label', ['Sex', 'br/',
                    tg('select.sex', [2 => ['Angel/Daemon', 'disabled'], 1 => 'Male', 0 => 'Female'])
                ]),
                tg(['input!text.field', 'readonly', 'title' => 'tooltip text'], 'Only for read'),
                tg('button', 'Send')
            ])
        ),

        tg('h2', 'Other tags example'),
        tg('.other-example', [
            tg(['a.hyperlink', 'href' => '#'], 'hyperlink'),
            'br/', 'br/', 'Image:', 'br/',
            tg('img.tiger', '/tigerbaby.jpg'),
            'br/', 'br/', 'SVG:', 'br/',
            tg(['svg', 'width' => 16, 'height' => 16, 'viewBox' => '0 0 16 16'],
                tg('path%d', 'M8.06 2C3 2 0 8 0 8s3 6 8.06 6c4.94 0 7.94-6 7.94-6S13 2 8.06 2z m-0.06 '
                    . '10c-2.2 0-4-1.78-4-4 0-2.2 1.8-4 4-4 2.22 0 4 1.8 4 4 0 2.22-1.78 4-4 4z m2-4c0 '
                    . '1.11-0.89 2-2 2s-2-0.89-2-2 0.89-2 2-2 2 0.89 2 2z')
            ),
            'br/', 'br/', 'List 1:', 'br/',
            tg('ul', ['item 1', 'item 2', 'item 3', 'item 4']),
            'br/', 'br/', 'List 2:', 'br/',
            tg('ol', ['item 1', 'item 2', 'item 3', 'item 4'])
        ]),

        tg('h2', 'Result'),
        tg('p', 'Source code of this page contain 2475 chars and result html page contain 2540 chars.'),

        tg('script%src', '/script.js'),
    ])
]);